a=bool(input("Enter The Value:-")) 
z=int(a)
print("value in int is:-",z)
print(type(z))
b=float(a)
print("value in float is:-",b)
print(type(b))
c=str(a)
print("value in str is:-",c)
print(type(c))
e=complex(a)
print("value in complex is:-",e)
print(type(e))
