a=int(input("Enter an int number-"))
b=float(a)
print("value in float is:-",b)
c=str(a)
print("value in str is:-",c)
d=bool(a)
print("value in boolian is:-",d)
e=complex(a)
print("value in complex is:-",e)
